# Generated by Django 5.1.6 on 2025-06-06 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("file_name", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("import_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("header", models.TextField()),
                ("footer", models.TextField()),
            ],
            options={
                "ordering": ["-import_time"],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mpan_core", models.BigIntegerField()),
                ("validation_status", models.CharField(max_length=1)),
                ("meter_id", models.CharField(max_length=10)),
                ("reading_type", models.CharField(max_length=1)),
                ("meter_register_id", models.CharField(max_length=2)),
                ("reading_datetime", models.DateTimeField()),
                ("register_reading", models.FloatField()),
                ("md_reset_datetime", models.DateTimeField(null=True)),
                ("nb_md_resets", models.IntegerField(null=True)),
                ("meter_reading_flag", models.BooleanField(null=True)),
                ("reading_method", models.CharField(max_length=1)),
                ("meter_reading_reason_code", models.CharField(max_length=2, null=True)),
                ("meter_reading_status", models.BooleanField(null=True)),
                (
                    "file_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.file"),
                ),
            ],
            options={
                "ordering": ["file_name","-reading_datetime"],
            },
        ),
    ]
